CREATE DATABASE NUMBER;
USE NUMBER;
CREATE TABLE T2(A INT ,
				B CHAR(10) );
DROP TABLE T2;
CALL NUM(10,"XXX");
CALL NUM(11,"YYY");

SELECT * FROM T2;
SHOW DATABASES;

CREATE DEFINER=`root`@`localhost` PROCEDURE `NUM`(I INT,J CHAR(10))
BEGIN
IF(SELECT A FROM T2 WHERE A LIKE (I))
THEN
INSERT INTO T2 (A,B) VALUES (NULL,NULL);
ELSE
INSERT INTO T2 (A,B) VALUES (I,J);
END IF;
END
