CREATE DATABASE DEPARTMENTS;
USE DEPARTMENTS;

CREATE TABLE DEPT(DEPTNO VARCHAR(10) NOT NULL,
DNAME VARCHAR(20) NOT NULL,
LOC VARCHAR(20) NOT NULL);
SELECT * FROM DEPT;
SELECT * FROM DEPARTMENT;
RENAME TABLE DEPT TO DEPARTMENT;

ALTER TABLE DEPARTMENT DROP COLUMN PINCODE;
SELECT * FROM DEPARTMENT;
ALTER TABLE DEPARTMENT CHANGE DNAME DEPT_NAME varchar(30);
ALTER TABLE DEPARTMENT MODIFY COLUMN LOC char(10);
SELECT * FROM DEPARTMENT;


USE DATABASENAME;
 SHOW TABLES;
 DROP TABLE department;
 USE DATABASENAME;
 SHOW TABLES;



