CREATE DATABASE EMPLO;
USE EMPLO;
 CREATE TABLE EMPLO1(
 E_ID VARCHAR(20) NOT NULL,
 E_NAME VARCHAR(20) NOT NULL,
 AGE INT(3) NOT NULL,
 SALARY INT(20) NOT NULL);
 
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("101","ANU","22","9000");
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("102","SHANE","29","8000");
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("103","ROHAN","34","6000");
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("104","SCOTT","44","10000");
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("105","TIGER","35","8000");
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("106","ALEX","27","7000");
 INSERT INTO  EMPLO1(E_ID, E_NAME,AGE,SALARY)VALUES("107","ABHI","29","8000");
 SELECT * FROM EMPLO1;
 SELECT COUNT(E_NAME) FROM EMPLO1;
 SELECT MAX(AGE) FROM EMPLO1;
 SELECT MIN(AGE) FROM EMPLO1;
 SELECT SUM(AGE) FROM EMPLO1;
 SELECT AVG(AGE) FROM EMPLO1;
 CREATE VIEW SONI AS
 SELECT AGE FROM EMPLO1;
 SELECT * FROM SONI;
 SELECT SALARY FROM EMPLO1 GROUP BY SALARY;
 SELECT SALARY FROM EMPLO1 ORDER BY SALARY ASC;
 SELECT SALARY FROM EMPLO1 ORDER BY SALARY DESC;